export const D1_SCHEMA = String.raw`
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS system_meta (key TEXT PRIMARY KEY,value TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sequences (prefix TEXT PRIMARY KEY,value INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS request_log (request_id TEXT PRIMARY KEY,module TEXT NOT NULL,result_json TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (USER_ID TEXT PRIMARY KEY,NAME TEXT,PIN_HASH TEXT,ROLE TEXT,PERM_RAW INTEGER DEFAULT 0,PERM_DYE INTEGER DEFAULT 0,PERM_PRODUCTION INTEGER DEFAULT 0,PERM_STITCHING INTEGER DEFAULT 0,PERM_QC INTEGER DEFAULT 0,PERM_REPORTS INTEGER DEFAULT 0,ADMIN INTEGER DEFAULT 0,ACTIVE INTEGER DEFAULT 1,FAILED_ATTEMPTS INTEGER DEFAULT 0,LOCKED_UNTIL TEXT,LAST_LOGIN TEXT,CREATED_AT TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS vendors (VENDOR_ID TEXT PRIMARY KEY,VENDOR_NAME TEXT,FABRIC_SUPPLIER INTEGER DEFAULT 0,DYE_VENDOR INTEGER DEFAULT 0,STITCHING_VENDOR INTEGER DEFAULT 0,CUTTING_VENDOR INTEGER DEFAULT 0,PHONE TEXT,GST_REF TEXT,ADDRESS TEXT,ACTIVE INTEGER DEFAULT 1,CREATED_AT TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS fabrics (FABRIC_ID TEXT PRIMARY KEY,FABRIC_NAME TEXT,FABRIC_CODE TEXT,UOM TEXT,ACTIVE INTEGER DEFAULT 1,NOTES TEXT,CREATED_AT TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS colors (COLOR_ID TEXT PRIMARY KEY,COLOR_NAME TEXT,COLOR_CODE TEXT,ACTIVE INTEGER DEFAULT 1,CREATED_AT TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS styles (STYLE_ID TEXT PRIMARY KEY,STYLE_NAME TEXT,CATEGORY TEXT,STYLE_CODE TEXT,DEFAULT_FABRIC_ID TEXT,ACTIVE INTEGER DEFAULT 1,NOTES TEXT,CREATED_AT TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS sizes (SIZE_ID TEXT PRIMARY KEY,SIZE_NAME TEXT,SORT_ORDER INTEGER DEFAULT 0,ACTIVE INTEGER DEFAULT 1,CREATED_AT TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS defect_reasons (DEFECT_ID TEXT PRIMARY KEY,DEFECT_NAME TEXT,STAGE TEXT,CATEGORY TEXT,ACTIVE INTEGER DEFAULT 1,NOTES TEXT,CREATED_AT TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS raw_inward (ROW_ID TEXT PRIMARY KEY,INWARD_ID TEXT,ROLL_ID TEXT UNIQUE,INWARD_DATE TEXT,SUPPLIER_ID TEXT,VENDOR_ROLL_NO TEXT,FABRIC_ID TEXT,INWARD_MTR REAL DEFAULT 0,INVOICE_CHALLAN TEXT,LOT_REF TEXT,STATUS TEXT,NOTES TEXT,CREATED_BY TEXT,CREATED_AT TEXT,UPDATED_BY TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS dye_jobs (ROW_ID TEXT PRIMARY KEY,DYE_BATCH_ID TEXT,ISSUE_DATE TEXT,DYE_VENDOR_ID TEXT,ROLL_ID TEXT,VENDOR_ROLL_NO TEXT,FABRIC_ID TEXT,COLOR_ID TEXT,ISSUE_MTR REAL DEFAULT 0,RECEIPT_DATE TEXT,RECEIVED_MTR REAL DEFAULT 0,SHRINKAGE_MTR REAL DEFAULT 0,DEFECT_MTR REAL DEFAULT 0,USABLE_MTR REAL DEFAULT 0,STATUS TEXT,DEFECT_REASON TEXT,NOTES TEXT,CREATED_BY TEXT,CREATED_AT TEXT,UPDATED_BY TEXT,UPDATED_AT TEXT,DYE_PLAN_ID TEXT);
CREATE TABLE IF NOT EXISTS dye_receipts (RECEIPT_ID TEXT PRIMARY KEY,DYE_BATCH_ID TEXT,RECEIPT_DATE TEXT,RECEIVED_MTR REAL DEFAULT 0,DEFECT_MTR REAL DEFAULT 0,USABLE_MTR REAL DEFAULT 0,VARIANCE_MTR REAL DEFAULT 0,FINAL_RECEIPT INTEGER DEFAULT 0,STATUS TEXT,DEFECT_REASON TEXT,NOTES TEXT,CREATED_BY TEXT,CREATED_AT TEXT,UPDATED_BY TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS production_batches (ROW_ID TEXT PRIMARY KEY,PRODUCTION_BATCH_ID TEXT UNIQUE,PLAN_DATE TEXT,DYE_BATCH_ID TEXT,STYLE_ID TEXT,FABRIC_ID TEXT,COLOR_ID TEXT,PLANNED_QTY REAL DEFAULT 0,ALLOCATED_MTR REAL DEFAULT 0,CUT_DATE TEXT,CONSUMED_MTR REAL DEFAULT 0,CUTTING_WASTE_MTR REAL DEFAULT 0,DEFECT_MTR REAL DEFAULT 0,M_CUT REAL DEFAULT 0,L_CUT REAL DEFAULT 0,XL_CUT REAL DEFAULT 0,"2XL_CUT" REAL DEFAULT 0,"3XL_CUT" REAL DEFAULT 0,OTHER_CUT REAL DEFAULT 0,TOTAL_CUT REAL DEFAULT 0,STATUS TEXT,NOTES TEXT,CREATED_BY TEXT,CREATED_AT TEXT,UPDATED_BY TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS stitching_jobs (ROW_ID TEXT PRIMARY KEY,CHALLAN_ID TEXT UNIQUE,ISSUE_DATE TEXT,STITCHING_VENDOR_ID TEXT,PRODUCTION_BATCH_ID TEXT,STYLE_ID TEXT,COLOR_ID TEXT,M_ISSUED REAL DEFAULT 0,L_ISSUED REAL DEFAULT 0,XL_ISSUED REAL DEFAULT 0,"2XL_ISSUED" REAL DEFAULT 0,"3XL_ISSUED" REAL DEFAULT 0,OTHER_ISSUED REAL DEFAULT 0,M_RECEIVED REAL DEFAULT 0,L_RECEIVED REAL DEFAULT 0,XL_RECEIVED REAL DEFAULT 0,"2XL_RECEIVED" REAL DEFAULT 0,"3XL_RECEIVED" REAL DEFAULT 0,OTHER_RECEIVED REAL DEFAULT 0,TOTAL_ISSUED REAL DEFAULT 0,TOTAL_RECEIVED REAL DEFAULT 0,PENDING_QTY REAL DEFAULT 0,STATUS TEXT,NOTES TEXT,CREATED_BY TEXT,CREATED_AT TEXT,UPDATED_BY TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS qc_events (QC_ID TEXT PRIMARY KEY,QC_DATE TEXT,CHALLAN_ID TEXT,PRODUCTION_BATCH_ID TEXT,VENDOR_ID TEXT,STYLE_ID TEXT,COLOR_ID TEXT,SIZE TEXT,QC_QTY REAL DEFAULT 0,PASS_QTY REAL DEFAULT 0,REWORK_QTY REAL DEFAULT 0,REJECT_QTY REAL DEFAULT 0,SHORT_QTY REAL DEFAULT 0,DEFECT_REASON TEXT,REWORK_CHALLAN_ID TEXT,REWORK_RETURNED_QTY REAL DEFAULT 0,FINAL_ACCEPTED_QTY REAL DEFAULT 0,STATUS TEXT,NOTES TEXT,CREATED_BY TEXT,CREATED_AT TEXT,UPDATED_BY TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS warehouse_handover (HANDOVER_ID TEXT PRIMARY KEY,HANDOVER_DATE TEXT,PRODUCTION_BATCH_ID TEXT,STYLE_ID TEXT,COLOR_ID TEXT,SIZE TEXT,ACCEPTED_QTY REAL DEFAULT 0,WAREHOUSE_RECEIVED_QTY REAL DEFAULT 0,PENDING_QTY REAL DEFAULT 0,WAREHOUSE_REF TEXT,STATUS TEXT,NOTES TEXT,CREATED_BY TEXT,CREATED_AT TEXT,UPDATED_BY TEXT,UPDATED_AT TEXT);
CREATE TABLE IF NOT EXISTS audit_log (AUDIT_ID TEXT PRIMARY KEY,TIMESTAMP TEXT,USER_ID TEXT,USER_NAME TEXT,ACTION TEXT,MODULE TEXT,RECORD_ID TEXT,OLD_VALUE_JSON TEXT,NEW_VALUE_JSON TEXT,DEVICE_INFO TEXT,IP_HASH TEXT);
CREATE TABLE IF NOT EXISTS settings (KEY TEXT PRIMARY KEY,VALUE TEXT,UPDATED_AT TEXT);

CREATE TABLE IF NOT EXISTS user_action_permissions (
  USER_ID TEXT NOT NULL,
  MODULE TEXT NOT NULL,
  CAN_VIEW INTEGER DEFAULT 1,
  CAN_CREATE INTEGER DEFAULT 1,
  CAN_EDIT INTEGER DEFAULT 1,
  CAN_CANCEL INTEGER DEFAULT 1,
  CAN_EXPORT INTEGER DEFAULT 1,
  CAN_AUDIT INTEGER DEFAULT 0,
  PRIMARY KEY(USER_ID,MODULE),
  FOREIGN KEY(USER_ID) REFERENCES users(USER_ID)
);
CREATE TABLE IF NOT EXISTS production_cut_lines (
  LINE_ID TEXT PRIMARY KEY,
  PRODUCTION_BATCH_ID TEXT NOT NULL,
  SIZE_ID TEXT NOT NULL,
  QTY INTEGER NOT NULL DEFAULT 0 CHECK(QTY>=0 AND QTY=CAST(QTY AS INTEGER)),
  CREATED_AT TEXT,
  UPDATED_AT TEXT,
  UNIQUE(PRODUCTION_BATCH_ID,SIZE_ID),
  FOREIGN KEY(PRODUCTION_BATCH_ID) REFERENCES production_batches(PRODUCTION_BATCH_ID),
  FOREIGN KEY(SIZE_ID) REFERENCES sizes(SIZE_ID)
);
CREATE TABLE IF NOT EXISTS stitching_issue_lines (
  LINE_ID TEXT PRIMARY KEY,
  CHALLAN_ID TEXT NOT NULL,
  SIZE_ID TEXT NOT NULL,
  QTY INTEGER NOT NULL DEFAULT 0 CHECK(QTY>=0 AND QTY=CAST(QTY AS INTEGER)),
  CREATED_AT TEXT,
  UPDATED_AT TEXT,
  UNIQUE(CHALLAN_ID,SIZE_ID),
  FOREIGN KEY(CHALLAN_ID) REFERENCES stitching_jobs(CHALLAN_ID),
  FOREIGN KEY(SIZE_ID) REFERENCES sizes(SIZE_ID)
);
CREATE TABLE IF NOT EXISTS stitching_receipts (
  RECEIPT_ID TEXT PRIMARY KEY,
  CHALLAN_ID TEXT NOT NULL,
  RECEIPT_DATE TEXT NOT NULL,
  STATUS TEXT NOT NULL DEFAULT 'RECEIVED',
  NOTES TEXT,
  CREATED_BY TEXT,
  CREATED_AT TEXT,
  UPDATED_BY TEXT,
  UPDATED_AT TEXT,
  FOREIGN KEY(CHALLAN_ID) REFERENCES stitching_jobs(CHALLAN_ID)
);
CREATE TABLE IF NOT EXISTS stitching_receipt_lines (
  LINE_ID TEXT PRIMARY KEY,
  RECEIPT_ID TEXT NOT NULL,
  CHALLAN_ID TEXT NOT NULL,
  SIZE_ID TEXT NOT NULL,
  QTY INTEGER NOT NULL DEFAULT 0 CHECK(QTY>=0 AND QTY=CAST(QTY AS INTEGER)),
  CREATED_AT TEXT,
  UPDATED_AT TEXT,
  UNIQUE(RECEIPT_ID,SIZE_ID),
  FOREIGN KEY(RECEIPT_ID) REFERENCES stitching_receipts(RECEIPT_ID),
  FOREIGN KEY(CHALLAN_ID) REFERENCES stitching_jobs(CHALLAN_ID),
  FOREIGN KEY(SIZE_ID) REFERENCES sizes(SIZE_ID)
);
CREATE TABLE IF NOT EXISTS rework_jobs (
  REWORK_ID TEXT PRIMARY KEY,
  QC_ID TEXT NOT NULL,
  CHALLAN_ID TEXT NOT NULL,
  PRODUCTION_BATCH_ID TEXT NOT NULL,
  VENDOR_ID TEXT,
  SIZE_ID TEXT NOT NULL,
  ISSUE_DATE TEXT NOT NULL,
  ISSUE_QTY INTEGER NOT NULL DEFAULT 0 CHECK(ISSUE_QTY>=0 AND ISSUE_QTY=CAST(ISSUE_QTY AS INTEGER)),
  RETURNED_QTY INTEGER NOT NULL DEFAULT 0 CHECK(RETURNED_QTY>=0 AND RETURNED_QTY=CAST(RETURNED_QTY AS INTEGER)),
  PASS_QTY INTEGER NOT NULL DEFAULT 0 CHECK(PASS_QTY>=0 AND PASS_QTY=CAST(PASS_QTY AS INTEGER)),
  REJECT_QTY INTEGER NOT NULL DEFAULT 0 CHECK(REJECT_QTY>=0 AND REJECT_QTY=CAST(REJECT_QTY AS INTEGER)),
  STATUS TEXT NOT NULL DEFAULT 'AT REWORK',
  NOTES TEXT,
  CREATED_BY TEXT,
  CREATED_AT TEXT,
  UPDATED_BY TEXT,
  UPDATED_AT TEXT,
  FOREIGN KEY(QC_ID) REFERENCES qc_events(QC_ID),
  FOREIGN KEY(CHALLAN_ID) REFERENCES stitching_jobs(CHALLAN_ID),
  FOREIGN KEY(PRODUCTION_BATCH_ID) REFERENCES production_batches(PRODUCTION_BATCH_ID),
  FOREIGN KEY(SIZE_ID) REFERENCES sizes(SIZE_ID)
);
CREATE TABLE IF NOT EXISTS warehouse_receipts (
  RECEIPT_ID TEXT PRIMARY KEY,
  HANDOVER_ID TEXT NOT NULL,
  RECEIPT_DATE TEXT NOT NULL,
  RECEIVED_QTY INTEGER NOT NULL DEFAULT 0 CHECK(RECEIVED_QTY>0 AND RECEIVED_QTY=CAST(RECEIVED_QTY AS INTEGER)),
  WAREHOUSE_REF TEXT,
  NOTES TEXT,
  STATUS TEXT NOT NULL DEFAULT 'RECEIVED',
  CREATED_BY TEXT,
  CREATED_AT TEXT,
  UPDATED_BY TEXT,
  UPDATED_AT TEXT,
  FOREIGN KEY(HANDOVER_ID) REFERENCES warehouse_handover(HANDOVER_ID)
);
CREATE TABLE IF NOT EXISTS resource_locks (
  RESOURCE_KEY TEXT PRIMARY KEY,
  REQUEST_ID TEXT,
  ACQUIRED_AT TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS app_errors (
  ERROR_ID TEXT PRIMARY KEY,
  TIMESTAMP TEXT NOT NULL,
  USER_ID TEXT,
  MODULE TEXT,
  MESSAGE TEXT,
  STACK TEXT,
  CONTEXT_JSON TEXT
);
CREATE INDEX IF NOT EXISTS idx_cutline_pb ON production_cut_lines(PRODUCTION_BATCH_ID);
CREATE INDEX IF NOT EXISTS idx_stitchline_challan ON stitching_issue_lines(CHALLAN_ID);
CREATE INDEX IF NOT EXISTS idx_stitchreceipt_challan ON stitching_receipts(CHALLAN_ID);
CREATE INDEX IF NOT EXISTS idx_stitchreceiptline_challan ON stitching_receipt_lines(CHALLAN_ID,SIZE_ID);
CREATE INDEX IF NOT EXISTS idx_rework_qc ON rework_jobs(QC_ID);
CREATE INDEX IF NOT EXISTS idx_rework_challan ON rework_jobs(CHALLAN_ID);
CREATE INDEX IF NOT EXISTS idx_whreceipt_handover ON warehouse_receipts(HANDOVER_ID);
CREATE INDEX IF NOT EXISTS idx_error_time ON app_errors(TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_raw_roll ON raw_inward(ROLL_ID);
CREATE INDEX IF NOT EXISTS idx_raw_fabric_status ON raw_inward(FABRIC_ID,STATUS);
CREATE INDEX IF NOT EXISTS idx_raw_inward ON raw_inward(INWARD_ID);
CREATE INDEX IF NOT EXISTS idx_dye_roll ON dye_jobs(ROLL_ID);
CREATE INDEX IF NOT EXISTS idx_dye_batch ON dye_jobs(DYE_BATCH_ID);
CREATE INDEX IF NOT EXISTS idx_dye_plan ON dye_jobs(DYE_PLAN_ID);
CREATE INDEX IF NOT EXISTS idx_dye_fc ON dye_jobs(FABRIC_ID,COLOR_ID);
CREATE INDEX IF NOT EXISTS idx_dye_receipt_batch ON dye_receipts(DYE_BATCH_ID);
CREATE INDEX IF NOT EXISTS idx_prod_dye ON production_batches(DYE_BATCH_ID);
CREATE INDEX IF NOT EXISTS idx_prod_style ON production_batches(STYLE_ID);
CREATE INDEX IF NOT EXISTS idx_stitch_prod ON stitching_jobs(PRODUCTION_BATCH_ID);
CREATE INDEX IF NOT EXISTS idx_stitch_vendor ON stitching_jobs(STITCHING_VENDOR_ID);
CREATE INDEX IF NOT EXISTS idx_qc_challan ON qc_events(CHALLAN_ID);
CREATE INDEX IF NOT EXISTS idx_qc_prod ON qc_events(PRODUCTION_BATCH_ID);
CREATE INDEX IF NOT EXISTS idx_hand_key ON warehouse_handover(PRODUCTION_BATCH_ID,STYLE_ID,COLOR_ID,SIZE);
CREATE INDEX IF NOT EXISTS idx_audit_time ON audit_log(TIMESTAMP);
`;
